wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/bedrock.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/brown_mushrooms.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/bush.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/button.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/button_hover.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/clouds.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/color0.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/color1.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/color2.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/color3.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/color4.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/color5.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/color6.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/color7.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/color8.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/color9.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/color10.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/color11.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/color12.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/color13.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/color14.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/color15.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/crosshair.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/dirt.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/glass.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/gold.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/grass.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/grass_dirt.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/gravel.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/hotbar_bg.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/hotbar_selection.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/lava.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/leaves_opaque.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/red_flower.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/red_mushroom.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/rock.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/rock_bronze.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/rock_coal.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/rock_gold.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/sand.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/sponge.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/stone.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/tree_side.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/tree_top.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/water.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/wood.png
wget -np -R "index.html" -r https://classic.minecraft.net/assets/textures/yellow_flower.png
